// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateFruit(ctx context.Context, name string) (Fruit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteFruit(ctx context.Context, id int64) error
	GetFruit(ctx context.Context, id int64) (Fruit, error)
	GetUser(ctx context.Context, email string) (User, error)
	ListFruits(ctx context.Context, arg ListFruitsParams) ([]Fruit, error)
	UpdateFruit(ctx context.Context, arg UpdateFruitParams) (Fruit, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
